# This file is the main config file for your Serverless lambda.

service: angryhuman-rss-generator

provider:
  name: aws
  runtime: nodejs4.3

functions:
  generaterss:
    handler: handler.generaterss
    events:
      - schedule: rate(1 hour)

resources:
  Resources:
    DataBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: angryhumanrss
        AccessControl: PublicRead
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: error.html
  Outputs:
    WebsiteURL:
      Value: { "Fn::GetAtt" : [ "DataBucket", "WebsiteURL" ] }
      Description: URL for the website hosted on S3
