# This file is the main config file for your Serverless lambda.

service: angryhuman-rss-generator

provider:
  name: aws
  runtime: nodejs4.3

functions:
 	generaterss:
		handler: handler.generaterss

	events:
		- schedule: rate(60 minutes)

resources:
  Resources:
    DataBucket:
      Type: AWS::S3::Bucket
				Properties:
					BucketName: angryhumanrss
